### ISSUE TITLE
DIGH 501 - Week 1

### ISSUE THREAD

**Issue by taylorcate** [taylorcate/NuttingVariorum#2]
Taking notes here because a lot of the info is central to what I'm trying to do in this project and I want my responses to be recorded and public.

**Comment by taylorcate** [comment]
## ["Public First,"](http://dhdebates.gc.cuny.edu/debates/text/83) by Sheila A. Brennan  
How do we define Digital Humanities and Public Digital Humanities?
Public DH holds the public at its core: 

> "Public digital humanities, then, should be identified by the ways that is engages with communities outside of the academy as a means for doing digital humanities scholarship." 

A presence on the web, i.e. essential public access, does not a "public" digital project make. Making the documentation open and engaging on social media with an intended audience is not enough: 

> "Doing any type of public digital humanities work requires an intentional decision from the beginning of the project that identifies, invites in, and addresses audience needs in the design, as well as the approach and content, long before the outreach for a finished project begins." 

Michael Frisch, "shared authority"; all public historians are the facilitators of the human record---the human record includes the ordinary people too.  

Roy Rosenzweig, brought public history to the digital sphere: opened the Center for History and New Media1 (1994). 

> "to use digital media to democratize history by incorporating multiple perspectives and inviting everyday citizens to contribute their own stories for new digital collections built to document major events and the histories of their own communities." 

### "Each public digital humanities project must begin by identifying audiences outside of the academy."

**Comment by taylorcate** [comment]
## ["Of Things Said and Unsaid: Power, Archival Silences, and Power in Silence,"](https://archivaria.ca/index.php/archivaria/article/view/12541) by Rodney G.S. Carter  

> “The technologies of silence/ The rituals, etiquette the blurring of terms/ silence not absence of words or music or even/ raw sounds Silence may be a plan/ rigorously executed the blueprint to a life It is a presence/ it has a history               a form Do not confuse it/ with any kind of absence.”  
Adrienne Rich, “Cartographies of Silence” (1975)

What is the purpose of the archive? 

> "Individuals may visit archives in order to hear the stories of their ancestors and predecessors, to learn of the past actions of their governments, and to examine the activities of private organizations." (216)

**Archival Power: "the power to allow voices to be heard."**
-Inclusion and exclusion as means to represent what "society" wants.  

Jacques Derrida "sees the archive as a place of violence":

> "The archive, as a reflection of and the source of state power, is extremely selective when deciding what gets in. Only those voices that conform to the ideals of those in power are allowed into the archive; those that do not conform are silenced. "  (219)

Anthropologist Susan Gal: 

> "silence traditionally is deplored as 'those who are denied speech cannot make their experience known and thus cannot influence the course of their lives or of history.'" (220)  

What we have archived is so miniscule in comparison to the actual human record. While archives can never feasibly represent the whole of society or the collective consciousness through material culture, it is their responsibility to try. 

Identity is informed by what is archived, and so the gaps and the absences of knowledge are incorporated into that identity just as what _is_ recorded shapes who that person or group of people becomes. 

Despite the silencing power of archives, they are still the means by which the marginalized bodies will "seek redress for the wrongdoings inflicted on them." (222)

> "Harris warns that archivists must not further marginalize the marginalized, we must resist the urge to speak for others, we must not romanticize them, and we must attempt to avoid reinforcing the marginalization by naming it" (226)

Feminist "silence" strategies state that in remaining silent---retaining our histories for ourselves and for our own consumption---we maintain control over them: 

> "This power is not “power over” where power is exerted by one group over another. Rather, this type of power may be seen as being “power with,” “power as capacity,” or “power to,” that as opposed to focussing on controlling others, deals with personal empowerment and control over the individual’s thoughts, feelings, and behaviours." (227)

**Natural and Unnatural Silences: "natural silences are those entered into by choice, often to allow for reflection and personal growth. Unnatural silences occur when the individual or group is silenced, through the use of power, both overt and covert." (228)**

**Comment by taylorcate** [comment]
## ["Digital History and Argument,"](https://rrchnm.org/argument-white-paper/) whitepaper by the Roy Rosenzweig Center for History and New Media

**Types of Digital History**

1. Digitizing and presenting historical sources online - this work is subversive of the hierarchical structures that govern archives because it allows the historian or web-capable researcher to draw hypertextual connections between collections. This is apparent even at the metadata level.

**Comment by taylorcate** [comment]
[DIGH 501 Syllabus Spring 2019.docx](https://github.com/taylorcate/NuttingVariorum/files/2761951/DIGH.501.Syllabus.Spring.2019.docx)

**Comment by RJP43** [comment]
I would like to contribute my notes via Hypothes.is for the "Digital History and Argument," whitepaper by the Roy Rosenzweig Center for History and New Media reading. My notes on the related workshop announcement are [here](https://hyp.is/go?url=https%3A%2F%2Frrchnm.org%2Fnews%2Farguing-with-digital-history-workshop-to-address-a-central-problem-in-digital-history%2F) and my notes on the whitepaper are [here](https://hyp.is/go?url=https%3A%2F%2Frrchnm.org%2Fwordpress%2Fwp-content%2Fuploads%2F2017%2F11%2Fdigital-history-and-argument.RRCHNM.pdf). To see my annotations you will need to have the Hypothes.is plugin and accept [this invitation](https://hypothes.is/groups/y779Zbyv/dh501) to the DH501 Hypothes.is group.
